### Builder Stage
FROM golang:1.25.1-alpine AS builder

WORKDIR /app

COPY go.mod .
RUN go mod download

COPY . .

#カレントディレクトリを/goappでビルド
RUN CGO_ENABLED=0 GOOS=linux go build -o /goapp .

### Final Stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates

COPY --from=builder /goapp /usr/local/bin/goapp

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/goapp"]